# Generated by Django 2.0.3 on 2018-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNo', models.CharField(max_length=10, unique=True)),
                ('CustmerName', models.CharField(max_length=10, unique=True)),
                ('Enable', models.IntegerField(blank=True, null=True)),
                ('DeviceId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
