# Generated by Django 2.0.3 on 2018-04-28 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CustmerName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='DeviceId',
            field=models.IntegerField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='MobileNo',
            field=models.CharField(max_length=10),
        ),
    ]
