# Generated by Django 2.0.3 on 2018-04-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20180428_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CustmerName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
