# Generated by Django 2.0.3 on 2018-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20180428_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CustmerName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='MobileNo',
            field=models.CharField(max_length=10),
        ),
    ]
