# Generated by Django 2.0.3 on 2018-04-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20180428_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='AmtOfWater',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
