# Generated by Django 2.0.3 on 2018-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_client_amtofwater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='MobileNo',
            field=models.IntegerField(),
        ),
    ]
