# Generated by Django 2.0.3 on 2018-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20180429_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='MobileNo',
            field=models.IntegerField(unique=True),
        ),
    ]
