# Generated by Django 2.0.3 on 2018-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20180429_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
