# Generated by Django 2.0.3 on 2018-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
